POST https://venkatasubbaraohow31njscadijbi.drops.nxtwave.tech/register/
Content-Type: application/json 

{
  "username": "adam_richard123",
  "password": "ri",
  "name": "Adam Richard",
  "gender": "male"
}

###

POST https://venkatasubbaraohow31njscadijbi.drops.nxtwave.tech/login/
Content-Type: application/json 

{
  "username":"JoeBiden",
  "password":"biden@123"
}

###

GET https://venkatasubbaraohow31njscadijbi.drops.nxtwave.tech/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MTgwMjM0MTl9.RXtLMqw8ntqBIKdwIdcA0WPG3h5Bz_Ya6M5JzL2_j4Q

###

GET https://venkatasubbaraohow31njscadijbi.drops.nxtwave.tech/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MTgwMjM0MTl9.RXtLMqw8ntqBIKdwIdcA0WPG3h5Bz_Ya6M5JzL2_j4Q

###

GET https://venkatasubbaraohow31njscadijbi.drops.nxtwave.tech/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MTgwMjM0MTl9.RXtLMqw8ntqBIKdwIdcA0WPG3h5Bz_Ya6M5JzL2_j4Q

###

GET https://venkatasubbaraohow31njscadijbi.drops.nxtwave.tech/tweets/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MTgwMjM0MTl9.RXtLMqw8ntqBIKdwIdcA0WPG3h5Bz_Ya6M5JzL2_j4Q

###

GET https://venkatasubbaraohow31njscadijbi.drops.nxtwave.tech/tweets/2/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MTgwMjM0MTl9.RXtLMqw8ntqBIKdwIdcA0WPG3h5Bz_Ya6M5JzL2_j4Q

###

GET https://venkatasubbaraohow31njscadijbi.drops.nxtwave.tech/tweets/2/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MTgwMjM0MTl9.RXtLMqw8ntqBIKdwIdcA0WPG3h5Bz_Ya6M5JzL2_j4Q

###
GET https://venkatasubbaraohow31njscadijbi.drops.nxtwave.tech/tweets/2/replies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MTgwMjM0MTl9.RXtLMqw8ntqBIKdwIdcA0WPG3h5Bz_Ya6M5JzL2_j4Q

###

GET https://venkatasubbaraohow31njscadijbi.drops.nxtwave.tech/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MTgwMjM0MTl9.RXtLMqw8ntqBIKdwIdcA0WPG3h5Bz_Ya6M5JzL2_j4Q

###

POST https://venkatasubbaraohow31njscadijbi.drops.nxtwave.tech/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MTgwMjM0MTl9.RXtLMqw8ntqBIKdwIdcA0WPG3h5Bz_Ya6M5JzL2_j4Q
Content-Type: application/json

{
   "tweet": "The Mornings..."
}

###

DELETE https://venkatasubbaraohow31njscadijbi.drops.nxtwave.tech/tweets/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MTgwMjM0MTl9.RXtLMqw8ntqBIKdwIdcA0WPG3h5Bz_Ya6M5JzL2_j4Q
  168 changes: 151 additions & 17 deletions168  